#!/bin/bash
# PrintJack System Help
# Usage: printjack-help or ~/PrintJack/help.sh

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}         PRINTJACK SYSTEM HELP${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

echo -e "${BLUE}Main Commands:${NC}"
echo "  printjack                    # Print capture only"
echo "  printjack --exfil            # Print capture + file server"
echo "  printjack --ducky            # Print capture + USB rubber ducky"
echo "  printjack --fuzz             # Print capture + USB port fuzzing"
echo "  printjack --exfil --ducky    # Exfil + ducky features"
echo "  printjack --exfil --fuzz     # Exfil + fuzzing features" 
echo "  printjack --help             # Show command options"
echo ""

echo -e "${BLUE}Individual Service Commands (Aliases):${NC}"
echo "  start-printjack       # Start USB printer gadget only"
echo "  capture-printjack     # Start capturing print jobs only"
echo "  convert-printjack     # Convert captured files to PDF"
echo "  printjack-exfil       # Start file exfiltration server only"
echo "  printjack-ducky       # Run USB rubber ducky only"
echo "  printjack-fuzz        # Run USB port fuzzing only"
echo "  printjack-help        # Show this help"
echo ""

echo -e "${BLUE}Manual Commands:${NC}"
echo "  cd ~/PrintJack"
echo "  sudo bash printjack.sh [--exfil] [--ducky] [--fuzz]  # Main script with options"
echo "  sudo bash start-printjack-gadget.sh                  # Start USB printer gadget"
echo "  sudo python3 printjack_capture.py                    # Start capturing print jobs"
echo "  python3 convert_captures.py captured_print_jobs/     # Convert to PDF"
echo "  sudo python3 printjack_exfil.py                      # Start file server"
echo "  python3 printjack_ducky.py                           # USB rubber ducky mode"
echo "  python3 printjack_ducky_fuzz.py                      # USB port fuzzing mode"
echo ""

echo -e "${BLUE}Usage Modes:${NC}"
echo ""
echo -e "${YELLOW}Mode 1: Print Capture Only${NC}"
echo "  sudo bash printjack.sh"
echo "  - Captures print jobs from target computer"
echo "  - Auto-converts to PDF in background"
echo ""
echo -e "${YELLOW}Mode 2: Print Capture + File Exfiltration${NC}"
echo "  sudo bash printjack.sh --exfil"
echo "  - All print capture features"
echo "  - Web server for file download at http://[pi-ip]"
echo "  - Target connects to same WiFi network"
echo ""
echo -e "${YELLOW}Mode 3: Print Capture + USB Rubber Ducky${NC}"
echo "  sudo bash printjack.sh --ducky"
echo "  - All print capture features"
echo "  - USB payload delivery system active"
echo ""
echo -e "${YELLOW}Mode 4: Print Capture + USB Port Fuzzing${NC}"
echo "  sudo bash printjack.sh --fuzz"
echo "  - All print capture features"
echo "  - Automatically fuzzes USB ports 1-10 to add printer"
echo "  - Attempts to auto-setup printer in Windows"
echo "  - Uses Microsoft XPS Document Writer driver"
echo ""
echo -e "${YELLOW}Mode 5: Full Feature Mode (Exfil + Ducky)${NC}"
echo "  sudo bash printjack.sh --exfil --ducky"
echo "  - All features: capture, exfiltration, and ducky"
echo "  - Note: Cannot use --ducky and --fuzz together"
echo ""
echo -e "${YELLOW}Mode 6: Full Feature Mode (Exfil + Fuzzing)${NC}"
echo "  sudo bash printjack.sh --exfil --fuzz"
echo "  - All features: capture, exfiltration, and port fuzzing"
echo "  - Note: Cannot use --ducky and --fuzz together"
echo ""

echo -e "${BLUE}Setup Steps - Print Capture:${NC}"
echo "1. Connect USB cable to target computer"
echo "2. Run: ${YELLOW}printjack${NC}"
echo "3. Add printer in Windows:"
echo "   - Use Microsoft XPS Document Writer driver"
echo "   - Select USB002 (Virtual printer port for USB)"
echo "4. Print documents to capture them"
echo "5. Files auto-convert to PDF in background"
echo ""

echo -e "${BLUE}Setup Steps - With File Exfiltration:${NC}"
echo "1. Connect Pi and target to same WiFi network"
echo "2. Run: ${YELLOW}printjack --exfil${NC}"
echo "3. Note the IP address shown (http://[pi-ip])"
echo "4. Set up printing (same as above)"
echo "5. Access files via browser from any device on network"
echo ""

echo -e "${BLUE}Setup Steps - With USB Rubber Ducky:${NC}"
echo "1. Connect USB cable to target computer"
echo "2. Run: ${YELLOW}printjack --ducky${NC}"
echo "3. Ducky payload system activates automatically"
echo "4. Print capture runs in parallel"
echo ""

echo -e "${BLUE}Setup Steps - With USB Port Fuzzing:${NC}"
echo "1. Connect USB cable to target computer"
echo "2. Run: ${YELLOW}printjack --fuzz${NC}"
echo "3. USB port fuzzing activates automatically"
echo "4. System attempts to auto-add printer on ports 1-10"
echo "5. Uses Microsoft XPS Document Writer driver"
echo "6. Print capture runs in parallel"
echo "7. No manual printer setup required (if successful)"
echo ""

echo -e "${BLUE}File Locations:${NC}"
echo "  Scripts:    ~/PrintJack/"
echo "  Commands:   ~/PrintJack/bin/"
echo "  Captured:   ~/PrintJack/captured_print_jobs/"
echo "  Converted:  ~/PrintJack/captured_print_jobs/converted/"
echo "  Logs:       ~/PrintJack/logs/"
echo ""

echo -e "${BLUE}System Services (Auto-Start):${NC}"
echo "  sudo systemctl enable printjack-capture   # Auto-start capture service"
echo "  sudo systemctl enable printjack-exfil     # Auto-start exfil server"
echo "  sudo systemctl start printjack-capture    # Start capture now"
echo "  sudo systemctl start printjack-exfil      # Start exfil server now"
echo "  sudo systemctl status printjack-capture   # Check capture status"
echo "  sudo systemctl status printjack-exfil     # Check exfil status"
echo ""

echo -e "${BLUE}Network Information:${NC}"
echo "  Pi IP Address: $(hostname -I | awk '{print $1}')"
echo "  Exfil server access: http://$(hostname -I | awk '{print $1}')"
echo "  File location: captured_print_jobs/converted/"
echo ""

echo -e "${BLUE}Process Management:${NC}"
echo "  ${YELLOW}View running processes:${NC}"
echo "    ps aux | grep printjack"
echo "  ${YELLOW}Stop all PrintJack services:${NC}"
echo "    sudo pkill -f printjack"
echo "  ${YELLOW}Stop specific service:${NC}"
echo "    sudo pkill -f printjack-exfil"
echo "    sudo pkill -f printjack-ducky"
echo "    sudo pkill -f printjack_ducky_fuzz"
echo ""

echo -e "${BLUE}Troubleshooting:${NC}"
echo "  ${RED}Gadget won't start:${NC} sudo reboot"
echo "  ${RED}USB issues:${NC} cat /sys/class/udc/20980000.usb/state"
echo "  ${RED}Device check:${NC} ls -la /dev/g_printer*"
echo "  ${RED}System logs:${NC} dmesg | tail -10"
echo "  ${RED}Port conflicts:${NC} sudo lsof -i :80 (or :8080)"
echo "  ${RED}Kill all services:${NC} sudo pkill -f printjack"
echo "  ${RED}Aliases not working:${NC} source ~/.bashrc"
echo "  ${RED}Permission errors:${NC} Check if running with sudo"
echo "  ${RED}Fuzzing not working:${NC} Check Windows driver compatibility"
echo "  ${RED}Ducky/Fuzz conflict:${NC} Only use one at a time"
echo ""

echo -e "${BLUE}Command Line Options:${NC}"
echo "  printjack.sh supports these flags:"
echo "    -e, --exfil    Enable file exfiltration server"
echo "    -d, --ducky    Enable USB rubber ducky functionality"
echo "    -f, --fuzz     Enable USB port fuzzing (auto-printer setup)"
echo "    -h, --help     Show command help"
echo ""
echo "  Examples:"
echo "    sudo bash printjack.sh"
echo "    sudo bash printjack.sh --exfil"
echo "    sudo bash printjack.sh --ducky" 
echo "    sudo bash printjack.sh --fuzz"
echo "    sudo bash printjack.sh --exfil --ducky"
echo "    sudo bash printjack.sh --exfil --fuzz"
echo ""
echo "  ${RED}Note:${NC} --ducky and --fuzz are mutually exclusive"
echo ""

echo -e "${BLUE}Supported Applications:${NC}"
echo "  ${GREEN}Works:${NC}     Microsoft Word, Notepad, Edge (with XPS driver)"
echo "  ${YELLOW}Limited:${NC}   Chrome, Adobe Acrobat (may only send control commands)"
echo ""

echo -e "${BLUE}File Formats Captured:${NC}"
echo "  .xps       XPS documents (from Microsoft XPS driver)"
echo "  .pdf       PDF files (direct PDF printing)"
echo "  .ps        PostScript files"
echo "  .txt       Plain text documents"
echo ""

echo -e "${BLUE}USB Port Fuzzing Details:${NC}"
echo "  - Automatically cycles through USB ports 1-10"
echo "  - Attempts to add PrintJack as a printer on each port"
echo "  - Uses Microsoft XPS Document Writer driver"
echo "  - Eliminates need for manual printer setup"
echo "  - Works by sending Windows printer installation commands"
echo "  - May take 1-2 minutes to complete full cycle"
echo "  - Success depends on Windows version and permissions"
echo ""

echo -e "${BLUE}Feature Comparison:${NC}"
echo "  ${YELLOW}USB Rubber Ducky:${NC}"
echo "    • Executes custom payload scripts"
echo "    • General-purpose HID attacks"
echo "    • Customizable commands"
echo ""
echo "  ${YELLOW}USB Port Fuzzing:${NC}"
echo "    • Specific to printer auto-setup"
echo "    • Automatically adds PrintJack printer"
echo "    • No manual configuration needed"
echo "    • Targets Windows printer subsystem"
echo ""

echo -e "${BLUE}Security Notes:${NC}"
echo "  - File exfiltration server runs on port 80 (requires sudo)"
echo "  - Server allows directory traversal for file access"
echo "  - Only run on trusted networks"
echo "  - Captured files may contain sensitive information"
echo "  - USB rubber ducky can execute commands on target"
echo "  - USB port fuzzing attempts system modification"
echo "  - Use responsibly and only on systems you own or have permission to test"
echo ""